### ISSUE TITLE
Are you going to support getUrl() ?

### ISSUE THREAD

**Issue by NiclasHedam** [Superbalist/flysystem-google-cloud-storage#31]
Are you going to support getUrl()? It is used by Laravel and Spark, and a change to illuminate/filesystem allows the driver to produce an URL for files now. It looks like it is going to be released with the next Laravel release.

[Source](https://github.com/illuminate/filesystem/commit/d567b2b961dd051063976c5246457b04d5dc29a)

**Comment by matthewgoslett** [comment]
Yes definitely.
We actually extended Laravel Storage on our side to add hacky support for object urls, so this change will tidy up a lot of the hackery we've had to do on our end.

**Comment by matthewgoslett** [comment]
Here are references in our laravel4-storage code base.
We allow for both:
getSignedUrl() - returns a temporary signed url to an object
see https://github.com/Superbalist/laravel4-storage/blob/master/src/Filesystem.php#L17

getPublicUrl() - returns a permanent url to a public object
see https://github.com/Superbalist/laravel4-storage/blob/master/src/Filesystem.php#L58

We could easily implement this for public urls.
It gets a little more tricky for signed urls.
We needed to extend the Google_Auth_OAuth2 class to expose the assertion credentials since these are needed in the signing process.
see https://github.com/Superbalist/laravel4-storage/blob/master/src/GoogleAuthOAuth2.php
see https://github.com/Superbalist/laravel4-storage/blob/master/src/StorageAdapterFactory.php#L81

Will implement when we have a moment.

Thanks

**Comment by matthewgoslett** [comment]
I've added support for `getUrl($path)` in the latest 3.0.1 release.
